import type { VehicleReferenceRecord } from './vehicle.types';

export const VEHICLE_REFERENCE_DATA: VehicleReferenceRecord[] = [
  {
    key: 'subaru-forester-2019',
    brand: 'Subaru',
    model: 'Forester',
    yearFrom: 2019,
    yearTo: 2025,
    bodyType: 'suv',
    drivetrain: 'awd',
    groundClearanceClass: 'high',
  },
  {
    key: 'subaru-brz-2022',
    brand: 'Subaru',
    model: 'BRZ',
    yearFrom: 2022,
    yearTo: 2025,
    bodyType: 'coupe',
    drivetrain: 'rwd',
    groundClearanceClass: 'low',
  },
  {
    key: 'fiat-egea-cross-2021',
    brand: 'Fiat',
    model: 'Egea Cross',
    yearFrom: 2021,
    yearTo: 2025,
    bodyType: 'suv',
    drivetrain: 'fwd',
    groundClearanceClass: 'medium',
  },
  {
    key: 'toyota-corolla-sedan-2019',
    brand: 'Toyota',
    model: 'Corolla Sedan',
    yearFrom: 2019,
    yearTo: 2025,
    bodyType: 'sedan',
    drivetrain: 'fwd',
    groundClearanceClass: 'low',
  },
  {
    key: 'volkswagen-golf-2017',
    brand: 'Volkswagen',
    model: 'Golf',
    yearFrom: 2017,
    yearTo: 2025,
    bodyType: 'hatchback',
    drivetrain: 'fwd',
    groundClearanceClass: 'low',
  },
  {
    key: 'honda-civic-sedan-2017',
    brand: 'Honda',
    model: 'Civic Sedan',
    yearFrom: 2017,
    yearTo: 2025,
    bodyType: 'sedan',
    drivetrain: 'fwd',
    groundClearanceClass: 'low',
  },
  {
    key: 'dacia-duster-4wd-2018',
    brand: 'Dacia',
    model: 'Duster 4x4',
    yearFrom: 2018,
    yearTo: 2025,
    bodyType: 'suv',
    drivetrain: '4wd',
    groundClearanceClass: 'high',
  },
  {
    key: 'suzuki-jimny-2019',
    brand: 'Suzuki',
    model: 'Jimny',
    yearFrom: 2019,
    yearTo: 2025,
    bodyType: 'suv',
    drivetrain: '4wd',
    groundClearanceClass: 'high',
  },
  {
    key: 'mini-countryman-2018',
    brand: 'Mini',
    model: 'Countryman',
    yearFrom: 2018,
    yearTo: 2025,
    bodyType: 'suv',
    drivetrain: 'awd',
    groundClearanceClass: 'medium',
  },
  {
    key: 'mercedes-c-coupe-2017',
    brand: 'Mercedes-Benz',
    model: 'C Coupe',
    yearFrom: 2017,
    yearTo: 2023,
    bodyType: 'coupe',
    drivetrain: 'rwd',
    groundClearanceClass: 'low',
  },
  {
    key: 'mazda-mx5-2016',
    brand: 'Mazda',
    model: 'MX-5',
    yearFrom: 2016,
    yearTo: 2025,
    bodyType: 'convertible',
    drivetrain: 'rwd',
    groundClearanceClass: 'low',
  },
];
